[project]
name = "yt-live-crash-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# loosened for tutorial compatibility
requires-python = ">=3.12,<3.13"
dependencies = []
